post_install() {
cat << EOF
===> You may want to load vboxguest, vboxsf and vboxvideo
EOF
    EXTRAMODULES='extramodules-3.2-jjk'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_upgrade() {
    EXTRAMODULES='extramodules-3.2-jjk'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-3.2-jjk'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}
